; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+7 on Fri May 26 2023 21:02:04 GMT+0800 (Singapore Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


