; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+7 on Fri May 26 2023 21:02:04 GMT+0800 (Singapore Standard Time)
G90				  ; absolute positioning
G1 H1 Z125		  ; move Z to top
G91             ; relative positioning
G1 H1 Y225 F1800 ; move quickly to Y axis endstop and stop there (first pass)
G1 H2 Y-5 F6000 ; go back a few mm
G1 H1 Y225 F360  ; move slowly to Y axis endstop once more (second pass)
G90             ; absolute positioning

