; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+7 on Fri May 26 2023 21:02:04 GMT+0800 (Singapore Standard Time)
G1 H1 Z120 F800        ; raise the Z to the highest position
G1 R1 X0 Y0            ; go to directly above position of the last print move
G1 R1 X0 Y0 Z0         ; go back to the last print move

