; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+7 on Fri May 26 2023 21:02:04 GMT+0800 (Singapore Standard Time)
; Wait for set temperatures to be reached
M116 P0

